version: '3.7'

services:
  
  consul-server:
    image: consul:latest
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      my_network:
        ipv4_address: 172.19.1.4

    command: "agent"

  consul-client:
    image: consul:latest
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    networks:
      my_network:
        ipv4_address: 172.19.1.5
    command: "agent"

networks:
  my_network:
    external: true

