# 需创建名为my_network的网络，一切配置按默认即可
# docker-compose -f docker-compose.yml up -d
version: '3.1'

networks:
  my_network:
    external: true

services:
  zoo1:
    image: zookeeper:3.5.9
    restart: always
    hostname: zoo1
    networks:
      my_network:
        ipv4_address: 172.19.1.1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:3.5.9
    restart: always
    hostname: zoo2
    networks:
      my_network:
        ipv4_address: 172.19.1.2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:3.5.9
    restart: always
    hostname: zoo3
    networks:
      my_network:
        ipv4_address: 172.19.1.3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181