server:
  port: 80

# 配置eureka默认关闭，通过profile确定究竟使用eureka还是zookeeper
eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:file:~/tmp/test_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #    type: com.alibaba.druid.pool.DruidDataSource
  h2:
    console:
      enabled: true
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: cloud-order-service

  # 配置zookeeper和ribbon默认关闭，通过profile确定究竟使用eureka还是zookeeper
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    zookeeper:
      enabled: false
    consul:
      enabled: false

  profiles:
    active: eureka