spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: zoo1:2181,zoo2:2181,zoo3:2181

  # 同时导入Eureka和Zookeeper的时候，好像会出一些篓子
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration
