server:
  port: 80

spring:
  datasource:
    url: jdbc:h2:file:~/tmp/test_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
#    type: com.alibaba.druid.pool.DruidDataSource
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: cloud-order-service

  profiles:
    active: eureka

