spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
      # 需要在hosts中配置 127.0.0.1 zoo1 zoo2 zoo3
      connect-string: zoo1:2181,zoo2:2182,zoo3:2183
    loadbalancer:
      ribbon:
        enabled: true