spring:
  cloud:
    zookeeper:
      connect-string: 172.19.1.1:2181,172.19.1.2:2181,172.19.1.3:2181
      enabled: true
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration
