spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: zoo1:2181,zoo2:2181,zoo3:2181
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration
